# _*_ coding: utf-8 _*_
#!/usr/bin/env python
# _*_ coding: cp1252 _*_
# _*_ cdoing: 850 _*_

#Bloque try: Permite probar un bloque de código en busca de errores.

#Bloque except: Permite manejar errores en caso de que estos ocurran.

#Imprimir una variable no declarada nos daría un error, para manejar ese tipo de errores:
#Caundo la variable si esta declarada
variable = "Correcto."

try:
	print(variable)
except:
	print("La variable no está declarada.")

#Cuando la variable no esta declarada	
try:
	print(variable1)
except:
	print("La variable no está declarada.")
	
#Ejemplo

reinicio = True

while reinicio: #ciclo que se cunplira siempre y cuando el reinicio sea = a true
	try:
		num1 = int(input("Introduce un número para multiplicar: ")) #Variable 1 asignada por el susuario 
		num2 = int(input("Introduce otro número para multiplicar: ")) #Variable 2 asignada por el usuario
	except ValueError:
		print("No has introducido un número. Vuelve a intentarlo.") #Excepcion: cuando el usuario no introduce ningun numero 
	else:
		print("El resultado es: ", num1 + num2) #En otro caso, el usuario si introducio 2 valores
	finally:
	    pregunta = input("¿Quieres seguir multiplicando? introduce S/N: \n") #Finalmente: pregunta si el reinicio será true o false
		
    if pregunta == "N": #Si es no, el programa termina
	    reinicio = False
    else:
		print("De acuerdo, vamos a seguir multiplicando.") #Si es si, el programa continua 